replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: latest
  pullPolicy: IfNotPresent
  command: ["/http-echo"]
  args: ["-text=Hello from data-service"]

service:
  type: ClusterIP
  port: 5678

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"

livenessProbe:
  httpGet:
    path: /
    port: 5678
readinessProbe:
  httpGet:
    path: /
    port: 5678

ingress:
  enabled: false

serviceAccount:
  create: true
  name: data-service-sa

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

image:
  repository: hashicorp/http-echo
  tag: "0.2.3"
  pullPolicy: IfNotPresent
  command: ["/http-echo"]
  args: ["-text=Hello from Data Service"]

