apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-service-rolebinding
  namespace: app
subjects:
  - kind: ServiceAccount
    name: data-service-sa
    namespace: app
roleRef:
  kind: Role
  name: role
  apiGroup: rbac.authorization.k8s.io

